repos:
    repo: local
    hooks:
        id: pylint
        name: pylint
        entry: pylint
        language: system
        types:  [python]
        args: 
        [
          "-rn", # Only display messages
          "-sn", # DonÂ´t display the score
          "--rcfile=.pylintrc", # Link to your config file
          "--load-plugind=pulint.extensions.docparams", # Load an extension
        ]